### ISSUE TITLE
create GCP account for project

### ISSUE THREAD

**Issue by raybuhr** [adi727/healthcare_cost#2]
## Google Cloud Platform (GCP)

In addition to having a really nice free-tier, GCP gives you $300 of credits valid for 12 months. This means you can run real cloud infrastructure without actually needing to front the bill. It also gives you an opportunity to try things out and learn without accidentally accruing costs. 

## Instructions

1. Create a new Google account for this project. You can name it whatever you want.
2. Check out Go to [https://cloud.google.com/free/](https://cloud.google.com/free/) to see what's available for free and what pricing looks like.
3. Go to the [GCP console](https://console.cloud.google.com). At the very top meny, click dropdown between the GCP logo and the search bar. Create a new project if one was not created for you.
4. Search for `IAM` and go the to `IAM & Admin` section. Click on the `IAM` menu option on the left sidebad, then click `Add users`. Add your personal google account as a `Project - Owner` so you can manage the GCP account without needing to login as this new project account. (Technically this is optional, but is a good habit and more similar to how you'd work in another organization). 
5. Add me as a user (my google account is in slack DM) as a `Project - Editor`.
6. Search for `billing` and go to the Billing section.
7. Select `Budgets & Alerts` from the left sidebar and add an alert to tell you when you hit 50%, 80% and 95% of your credits ($300). Feel free to add any other alerts you want. This is a good tool to make sure you don't leave something expensive on, but also as a reminder for what you have left. 
8. Install the [GCP command line tool `gcloud`](https://cloud.google.com/sdk/)
9. Login to GCP from the command line by running `gcloud auth login`. This will automatically pop open browser window asking you to sign in and/or or allow Google to access your account.
10. Verify this worked by running `gcloud projects list` and ensuring that you can see the project you created.

**Comment by adi727** [comment]
Quick note: GCP only works with Python 2.7. Learned how to install both Python 3.x and Python 2.7 which was nice! https://datascience.com.co/how-to-install-python-2-7-and-3-6-in-windows-10-add-python-path-281e7eae62a

**Comment by raybuhr** [comment]
Oh wow, I forgot to check on that. I guess I assumed they would add have made `gcloud` available in either already. Glad you got that figured out, though!
