### ISSUE TITLE
Decide on your blog tool

### ISSUE THREAD

**Issue by raybuhr** [adi727/healthcare_cost#6]
Part of the mentorship program is sharing your journey with the public. It might sound scary, it might sound exciting. It's really just an opportunity to practice. 

There are two blogging tools I would recommend, each with very different tradeoffs:
- **GitHub pages**
    - free web hosting and you own your posts
    - built into GitHub so can use this project repo
    - you can practice writing as much or as little code for the website as you want, depending on what dev tools you pick to build it (I like [Hugo](https://gohugo.io/) but it's not python. There is [mkdocs](https://www.mkdocs.org/#getting-started) and [pelican](https://blog.getpelican.com/) which are python and also easy to use.). 
- **Medium**
    - free web hosting, but you don't own your posts
    - can get much more traffic/eyeballs on your posts due to Medium community/network
    - low code (you just write markdown or using their web GUI)

I'm more than happy to discuss either of these options or alternatives with you in more detail. One thing I would like to state for the record is to remember the _Zen of Python_ and specifically:

> Simple is better than complex.
> Complex is better than complicated.

**Comment by adi727** [comment]
Medium will be my choice for now
